### ISSUE TITLE
Getting "Error 4; details: 500: Internal Server Error" after following instructions

### ISSUE THREAD

**Issue by object404** [google/vogon#13]
Hi. We're testing out Vogon on a fresh installation of the latest version of Ubuntu, 19.10, updated to the latest patches/files.

We've followed all the instructions in the guide on this Github project's front page, and we're getting the following error when we try to "Save & generate a preview for row" or "Save & generate all video variations" in the "Video config" tab:

"Error 4; details: 500: Internal Server Error"

The Google sheet is properly linked, being an upload of feed.csv from the base_project folder.

These are the logs on terminal:

```convert -background transparent -colorspace sRGB -font '/home/ubuntu/vogon_app/vogon/projects/hiro/assets/Rye-Regular.ttf' -pointsize 88.0 -fill '#0FAAF0' label:@/tmp/vogon_xdba7yar.txt /tmp/vogon_q3yjlyh0.png
Traceback (most recent call last):
  File "/home/ubuntu/vogon_app/vogon/third_party/bottle/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/ubuntu/vogon_app/vogon/third_party/bottle/bottle.py", line 1729, in wrapper
    rv = callback(*a, **ka)
  File "server.py", line 129, in generate_preview
    project_dir=project_folder)
  File "/home/ubuntu/vogon_app/vogon/vogon.py", line 190, in generate_preview
    project_dir)
  File "/home/ubuntu/vogon_app/vogon/vogon.py", line 198, in generate_video
    complex_filters, txt_input_files = filter_strings(image_overlays, text_overlays)
  File "/home/ubuntu/vogon_app/vogon/vogon.py", line 254, in filter_strings
    output_stream)
  File "/home/ubuntu/vogon_app/vogon/vogon.py", line 526, in text_filter
    is_cropped_text)
  File "/home/ubuntu/vogon_app/vogon/vogon.py", line 603, in write_temp_image
    rs = subprocess.check_output(' '.join(args), stderr=subprocess.STDOUT, shell=True)
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'convert -background transparent -colorspace sRGB -font '/home/ubuntu/vogon_app/vogon/projects/hiro/assets/Rye-Regular.ttf' -pointsize 88.0 -fill '#0FAAF0' label:@/tmp/vogon_xdba7yar.txt /tmp/vogon_q3yjlyh0.png' returned non-zero exit status 1.
127.0.0.1 - - [21/Apr/2020 01:47:28] "GET /api/projects/TestProject1/preview/row/1?0.986307353121652 HTTP/1.1" 500 2754```

Any clues on what to do?

**Comment by object404** [comment]
I noticed that the "hiro" folder inside the projects folder in '/home/ubuntu/vogon_app/vogon/projects/hiro/assets/Rye-Regular.ttf' didn't exist, so I tried manually creating a 'hiro" folder inside the projects folder and copying the assets folder there to see if it would fix things, but I still get the same result.

**Comment by rzdev** [comment]
@object404 Hi, have you found the solution?

**Comment by object404** [comment]
Nope, haven't been able to make it work on Ubuntu.
